#!/usr/bin/env bash
# Emit a makefile with per-assistant env-var wiring to ./makefile.
#
# Usage: generate-makefile.sh <nick> <gws_config_dir_or_empty> <gh_user_or_empty> <agent_command> [--force]
#
# Both gws_config_dir and gh_user are independently optional. If either is
# empty, the generated makefile omits that env export from the 'run' recipe.
#
# Refuses to overwrite an existing ./makefile unless --force is passed so
# re-running /setup can't silently clobber the user's edits.

set -euo pipefail

if [[ $# -lt 4 || $# -gt 5 ]]; then
  echo "Usage: $0 <nick> <gws_config_dir_or_empty> <gh_user_or_empty> <agent_command> [--force]" >&2
  exit 64
fi

NICK="$1"
GWS_CONFIG_DIR="$2"
GH_USER="$3"
AGENT_COMMAND="$4"
FORCE="${5:-}"

if [[ -n "$FORCE" && "$FORCE" != "--force" ]]; then
  echo "ERROR: fifth arg must be --force or omitted (got: $FORCE)" >&2
  exit 64
fi

if [[ -z "$NICK" ]]; then
  echo "ERROR: nick must not be empty" >&2
  exit 64
fi

if [[ -z "$AGENT_COMMAND" ]]; then
  echo "ERROR: agent command must not be empty" >&2
  exit 64
fi

REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
OUT="$REPO_ROOT/makefile"

if [[ -f "$OUT" && "$FORCE" != "--force" ]]; then
  echo "ERROR: $OUT already exists; pass --force to overwrite" >&2
  exit 1
fi

# Assemble the recipe env prefix lines conditionally. Each line ends with
# backslash for make line-continuation; the final line continues into the
# 'claude ...' command on its own logical recipe line.
ENV_LINES=""
if [[ -n "$GH_USER" ]]; then
  ENV_LINES+="	GH_TOKEN=\$\$(gh auth token --user \$(GH_USER)) \\
"
fi
if [[ -n "$GWS_CONFIG_DIR" ]]; then
  ENV_LINES+="	GOOGLE_WORKSPACE_CLI_CONFIG_DIR=\$(GOOGLE_WORKSPACE_CLI_CONFIG_DIR) \\
"
fi

# Assemble top-level variable defaults.
VAR_LINES="NICK ?= $NICK
"
if [[ -n "$GWS_CONFIG_DIR" ]]; then
  VAR_LINES+="GOOGLE_WORKSPACE_CLI_CONFIG_DIR ?= \$(HOME)/.config/$GWS_CONFIG_DIR
"
fi
if [[ -n "$GH_USER" ]]; then
  VAR_LINES+="GH_USER ?= $GH_USER
"
fi

cat > "$OUT" <<EOF
# Auto-generated by /setup. Edit freely — /setup will refuse to overwrite this
# file once it exists unless you delete it first.
$VAR_LINES
.PHONY: run check-links check-links-all
run:
$ENV_LINES		$AGENT_COMMAND

check-links:
	lychee --offline --include-fragments --config lychee.toml './**/*.md'

check-links-all:
	lychee --include-fragments --config lychee.toml './**/*.md'
EOF

echo "wrote $OUT"
